package ru.nsu.fit.popov.medicineclock.model.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import ru.nsu.fit.popov.medicineclock.model.db.SysDate;
import ru.nsu.fit.popov.medicineclock.model.db.Medicine;
import ru.nsu.fit.popov.medicineclock.model.db.Logging;

import ru.nsu.fit.popov.medicineclock.model.db.SysDateDao;
import ru.nsu.fit.popov.medicineclock.model.db.MedicineDao;
import ru.nsu.fit.popov.medicineclock.model.db.LoggingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sysDateDaoConfig;
    private final DaoConfig medicineDaoConfig;
    private final DaoConfig loggingDaoConfig;

    private final SysDateDao sysDateDao;
    private final MedicineDao medicineDao;
    private final LoggingDao loggingDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sysDateDaoConfig = daoConfigMap.get(SysDateDao.class).clone();
        sysDateDaoConfig.initIdentityScope(type);

        medicineDaoConfig = daoConfigMap.get(MedicineDao.class).clone();
        medicineDaoConfig.initIdentityScope(type);

        loggingDaoConfig = daoConfigMap.get(LoggingDao.class).clone();
        loggingDaoConfig.initIdentityScope(type);

        sysDateDao = new SysDateDao(sysDateDaoConfig, this);
        medicineDao = new MedicineDao(medicineDaoConfig, this);
        loggingDao = new LoggingDao(loggingDaoConfig, this);

        registerDao(SysDate.class, sysDateDao);
        registerDao(Medicine.class, medicineDao);
        registerDao(Logging.class, loggingDao);
    }
    
    public void clear() {
        sysDateDaoConfig.clearIdentityScope();
        medicineDaoConfig.clearIdentityScope();
        loggingDaoConfig.clearIdentityScope();
    }

    public SysDateDao getSysDateDao() {
        return sysDateDao;
    }

    public MedicineDao getMedicineDao() {
        return medicineDao;
    }

    public LoggingDao getLoggingDao() {
        return loggingDao;
    }

}
