package ru.nsu.fit.popov.medicineclock.model.db;

import org.greenrobot.greendao.annotation.*;

import ru.nsu.fit.popov.medicineclock.model.db.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "LOGGING".
 */
@Entity(active = true)
public class Logging {

    @Id(autoincrement = true)
    private Long id;
    private java.util.Date date;
    private String type;
    private Long medicineID;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient LoggingDao myDao;

    @ToOne(joinProperty = "medicineID")
    private Medicine medicine;

    @Generated
    private transient Long medicine__resolvedKey;

    @Generated
    public Logging() {
    }

    public Logging(Long id) {
        this.id = id;
    }

    @Generated
    public Logging(Long id, java.util.Date date, String type, Long medicineID) {
        this.id = id;
        this.date = date;
        this.type = type;
        this.medicineID = medicineID;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getLoggingDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Long getMedicineID() {
        return medicineID;
    }

    public void setMedicineID(Long medicineID) {
        this.medicineID = medicineID;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public Medicine getMedicine() {
        Long __key = this.medicineID;
        if (medicine__resolvedKey == null || !medicine__resolvedKey.equals(__key)) {
            __throwIfDetached();
            MedicineDao targetDao = daoSession.getMedicineDao();
            Medicine medicineNew = targetDao.load(__key);
            synchronized (this) {
                medicine = medicineNew;
            	medicine__resolvedKey = __key;
            }
        }
        return medicine;
    }

    @Generated
    public void setMedicine(Medicine medicine) {
        synchronized (this) {
            this.medicine = medicine;
            medicineID = medicine == null ? null : medicine.getId();
            medicine__resolvedKey = medicineID;
        }
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
