package ru.nsu.fit.popov.medicineclock.model.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "MEDICINE".
 */
@Entity
public class Medicine {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    @Unique
    private String name;
    private boolean active;
    private int startTime;
    private int delay;
    private int count;

    @Generated
    public Medicine() {
    }

    public Medicine(Long id) {
        this.id = id;
    }

    @Generated
    public Medicine(Long id, String name, boolean active, int startTime, int delay, int count) {
        this.id = id;
        this.name = name;
        this.active = active;
        this.startTime = startTime;
        this.delay = delay;
        this.count = count;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    public boolean getActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public int getStartTime() {
        return startTime;
    }

    public void setStartTime(int startTime) {
        this.startTime = startTime;
    }

    public int getDelay() {
        return delay;
    }

    public void setDelay(int delay) {
        this.delay = delay;
    }

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }

}
