package ru.nsu.fit.popov.medicineclock.model.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SYS_DATE".
 */
@Entity
public class SysDate {

    @Id(autoincrement = true)
    private Long id;
    private Boolean active;

    @Generated
    public SysDate() {
    }

    public SysDate(Long id) {
        this.id = id;
    }

    @Generated
    public SysDate(Long id, Boolean active) {
        this.id = id;
        this.active = active;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

}
